# docker-compose.yml

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8080

  backend:
    build: ../backend  # Path to your backend Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/mediaapp
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=mediauser
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=mediaapp
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: