version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: media-postgres
    restart: always
    environment:
      POSTGRES_USER: mediauser
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: mediaapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  media-app:
    image: raifaisalhussain/openverse-media-search:latest   # Replace with your Docker Hub image
    container_name: media-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mediaapp
      SPRING_DATASOURCE_USERNAME: mediauser
      SPRING_DATASOURCE_PASSWORD: test123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  postgres-data: