name: Docker CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Show directory structure for debug
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "--- backend directory ---"
          ls -la backend

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Backend with Maven
        run: |
          ls -la
          if [ -f "pom.xml" ]; then
            echo "Found pom.xml in root, proceeding with build..."
            mvn clean package -DskipTests
          else
            echo "ERROR: pom.xml not found in expected location!"
            exit 1
          fi

      - name: Build Docker Images with Docker Compose
        run: docker compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Image
        run: |
          docker tag openverse-media-search-backend ${{ secrets.DOCKER_USERNAME }}/openverse-media-search-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/openverse-media-search-backend:latest

      - name: Push Frontend Image
        run: |
          docker tag openverse-media-search-frontend ${{ secrets.DOCKER_USERNAME }}/openverse-media-search-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/openverse-media-search-frontend:latest
